### ISSUE TITLE
Delayed chart rendering

### ISSUE THREAD

**Issue by lucasnantonio** [lucasnantonio/ff#19]
We got a few render cycle issues going on:

- [x]  On first render, chart has no data even though there is data on state.
(edit: fixed, see https://github.com/lucasnantonio/ff/commit/63ab81c526af0690f850c44cda5a6ffaf638e6c2, is this acceptable ?)
- [x]  Also, chart needs 2 updates to show the retirement Icon. Doesn't appear on first or second render.
- [x]  Lastly, life events get rendered one cycle late

@rodrigorahal can you teach us some wizardry here?

**Comment by rodrigorahal** [comment]
About life events getting rendered one cycle late:

the lifecycle method was defined like this:
```javascript
componentDidUpdate(nextProps) {
    this.updateChart(nextProps.retirementResults);
  }
```
But the React [componentDidUpdate](https://reactjs.org/docs/react-component.html#componentdidupdate) lifecycle method does not receive `nextProps`, in fact, it receives `prevProps`.
So we were just renaming the `prevProps` to `nextProps`.
The fix is simple:
```javascript
componentDidUpdate() {
    // as the name of methods says, the component has already updated
    // so we can just use this.props :)
    // and safelly ignore the prevProps and prevState
    this.updateChart(this.props.retirementResults);
  }
```

**Comment by rodrigorahal** [comment]
About the retirement icon:

Moving the function call outside the returned object seems to work:
```javascript
        ...
        const retirementIcon = this.getIcon();
        return {
          label,
          data: [{
            x: data.retirement.age / 12,
            y: data.retirement.balance,
          }],
          pointStyle: retirementIcon,
          pointHoverRadius: 0,
          borderColor: 'rgba(0, 0, 0, 1)',
        };
```
I'm not exactly sure why this works.
My intuition is that creating an image involves some kind of loading.
And moving it outside the returned object makes it load before chartjs tries to render it.
Ref: [Creating an image from scratch](https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Using_images#Creating_an_image_from_scratch)
